/*
 *  Copyright (c) 2011, StripBandunk and/or its affiliates. All rights reserved.
 * 
 *       http://stripbandunk.com/
 * 
 *  STRIPBANDUNK PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * TransitionDialog.java
 *
 * Created on Sep 2, 2011, 1:48:28 PM
 */
package com.stripbandunk.test.jglasspane.transition;

import com.stripbandunk.jglasspane.JGlassPane;
import com.stripbandunk.jglasspane.component.TransitionComponent;
import com.stripbandunk.jglasspane.helper.GraphicHelper;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Paint;
import java.awt.Rectangle;
import javax.swing.JColorChooser;

/**
 *
 * @author echo
 */
public abstract class TransitionDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    private JGlassPane glassPane;

    private TransitionComponent transitionComponent;

    /** Creates new form TransitionDialog
     * @param parent
     * @param modal  
     */
    public TransitionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        glassPane = new JGlassPane();
        setGlassPane(glassPane);

        // Tampilkan GlassPane
        getGlassPane().setVisible(true);

        transitionComponent = new TransitionComponent();
        glassPane.addGlassPaneComponent(transitionComponent);

        setLocationRelativeTo(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorChooser = new javax.swing.JColorChooser();
        panelContainer = new javax.swing.JPanel();
        panelIdentity = new com.stripbandunk.test.jglasspane.panel.PanelIdentity();
        panelTable = new com.stripbandunk.test.jglasspane.panel.PanelTable();
        buttonInpu = new javax.swing.JButton();
        buttonTable = new javax.swing.JButton();
        buttonColor = new javax.swing.JButton();
        panelColor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelContainer.setLayout(new java.awt.CardLayout());
        panelContainer.add(panelIdentity, "identity");
        panelContainer.add(panelTable, "table");

        buttonInpu.setText("Input Form");
        buttonInpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInpuActionPerformed(evt);
            }
        });

        buttonTable.setText("Table");
        buttonTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTableActionPerformed(evt);
            }
        });

        buttonColor.setText("Color");
        buttonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColorActionPerformed(evt);
            }
        });

        panelColor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Color", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));

        javax.swing.GroupLayout panelColorLayout = new javax.swing.GroupLayout(panelColor);
        panelColor.setLayout(panelColorLayout);
        panelColorLayout.setHorizontalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        panelColorLayout.setVerticalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonTable, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(buttonInpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonColor, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonInpu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonColor)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void buttonInpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInpuActionPerformed
    // TODO add your handling code here:
    Rectangle rectangle = GraphicHelper.getClip(panelContainer, transitionComponent);
    Paint paint = panelColor.getBackground();
    startTransition(rectangle, paint);
    showInputForm();
}//GEN-LAST:event_buttonInpuActionPerformed

private void buttonTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTableActionPerformed
    // TODO add your handling code here:
    Rectangle rectangle = GraphicHelper.getClip(panelContainer, transitionComponent);
    Paint paint = panelColor.getBackground();
    startTransition(rectangle, paint);
    showTableForm();
}//GEN-LAST:event_buttonTableActionPerformed

private void buttonColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColorActionPerformed
    // TODO add your handling code here:
    Color color = JColorChooser.showDialog(this, "Choose Color", panelColor.getBackground());
    if (color != null) {
        panelColor.setBackground(color);
    }
}//GEN-LAST:event_buttonColorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonColor;
    private javax.swing.JButton buttonInpu;
    private javax.swing.JButton buttonTable;
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.JPanel panelColor;
    private javax.swing.JPanel panelContainer;
    private com.stripbandunk.test.jglasspane.panel.PanelIdentity panelIdentity;
    private com.stripbandunk.test.jglasspane.panel.PanelTable panelTable;
    // End of variables declaration//GEN-END:variables

    public void showInputForm() {
        CardLayout layout = (CardLayout) panelContainer.getLayout();
        layout.show(panelContainer, "identity");
    }

    public void showTableForm() {
        CardLayout layout = (CardLayout) panelContainer.getLayout();
        layout.show(panelContainer, "table");
    }

    public TransitionComponent getTransitionComponent() {
        return transitionComponent;
    }

    public abstract void startTransition(Rectangle rectangle, Paint paint);
}
