/*
 *  Copyright (c) 2011, StripBandunk and/or its affiliates. All rights reserved.
 * 
 *       http://stripbandunk.com/
 * 
 *  STRIPBANDUNK PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * TransitionDialog.java
 *
 * Created on Sep 2, 2011, 1:48:28 PM
 */
package com.stripbandunk.test.jglasspane.transition.image;

import com.stripbandunk.jglasspane.JGlassPane;
import com.stripbandunk.jglasspane.component.ImageTransitionComponent;
import com.stripbandunk.jglasspane.helper.GraphicHelper;
import com.stripbandunk.jglasspane.transition.image.creator.ComponentImageCreator;
import com.stripbandunk.jglasspane.transition.image.creator.ImageCreator;
import java.awt.CardLayout;
import java.awt.Point;

/**
 *
 * @author echo
 */
public abstract class ImageTransitionDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    private JGlassPane glassPane;

    private ImageTransitionComponent imageTransitionComponent;

    private ImageCreator imageCreator;

    /** Creates new form TransitionDialog
     * @param parent
     * @param modal  
     */
    public ImageTransitionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        glassPane = new JGlassPane();
        setGlassPane(glassPane);

        // Tampilkan GlassPane
        getGlassPane().setVisible(true);

        imageTransitionComponent = new ImageTransitionComponent();
        glassPane.addGlassPaneComponent(imageTransitionComponent);

        imageCreator = new ComponentImageCreator(panelContainer);
        imageTransitionComponent.setImageCreator(imageCreator);

        setLocationRelativeTo(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContainer = new javax.swing.JPanel();
        panelIdentity = new com.stripbandunk.test.jglasspane.panel.PanelIdentity();
        panelTable = new com.stripbandunk.test.jglasspane.panel.PanelTable();
        buttonInpu = new javax.swing.JButton();
        buttonTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelContainer.setLayout(new java.awt.CardLayout());
        panelContainer.add(panelIdentity, "identity");
        panelContainer.add(panelTable, "table");

        buttonInpu.setText("Input Form");
        buttonInpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInpuActionPerformed(evt);
            }
        });

        buttonTable.setText("Table");
        buttonTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonTable, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(buttonInpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(buttonInpu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTable)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void buttonInpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInpuActionPerformed
    // TODO add your handling code here:
    Point location = GraphicHelper.getLocation(panelContainer, imageTransitionComponent);
    startTransition(location);
    showInputForm();
}//GEN-LAST:event_buttonInpuActionPerformed

private void buttonTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTableActionPerformed
    // TODO add your handling code here:
    Point location = GraphicHelper.getLocation(panelContainer, imageTransitionComponent);
    startTransition(location);
    showTableForm();
}//GEN-LAST:event_buttonTableActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInpu;
    private javax.swing.JButton buttonTable;
    private javax.swing.JPanel panelContainer;
    private com.stripbandunk.test.jglasspane.panel.PanelIdentity panelIdentity;
    private com.stripbandunk.test.jglasspane.panel.PanelTable panelTable;
    // End of variables declaration//GEN-END:variables

    public void showInputForm() {
        CardLayout layout = (CardLayout) panelContainer.getLayout();
        layout.show(panelContainer, "identity");
    }

    public void showTableForm() {
        CardLayout layout = (CardLayout) panelContainer.getLayout();
        layout.show(panelContainer, "table");
    }

    public ImageTransitionComponent getImageTransitionComponent() {
        return imageTransitionComponent;
    }

    public abstract void startTransition(Point location);
}
